# i think this gets the remote cfg as a baseline
# === BASE === 
#_BASE_: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml

# === MODEL === 
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1

# === SOLVER === #
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00005
  MAX_ITER: 8000

# === DATASET === #
DATASETS:
  TRAIN: ("jersey_royal_train",)
  TEST: ("jersey_royal_val",)
  
# === DATALOADER === #
DATALOADER:
  NUM_WORKERS: 2

# === TEST === #
TEST:
  EVAL_PERIOD: 160

# === OUTPUT === #
OUTPUT_DIR: "outputs/DEV_TEST_1"